#
# Your Crowdin credentials
# Reference: https://support.crowdin.com/configuration-file/
#
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

#
# Files configuration
#
files: [
  {
    "source": "/README.md",
    "translation": "/README_%locale%.md",
    "languages_mapping": {
        "locale": {
            "es-ES": "es",
            "zh-CN": "zh-Hans"
        }
    }
  },
]
