name: Crowdin Action

on:
  push:
    branches: [main]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crowdin action
        uses: crowdin/github-action@1.4.9
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          push_translations: true
          localization_branch_name: l10n_crowdin_action
          create_pull_request: true
          pull_request_labels: 'documentation'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
